project:
  type: website
  output-dir: docs
  resources:
    - .nojekyll
    - images/

website:
  title: "Eduardo Pagés"
  site-url: "https://eduard7central.github.io"
  description: "Political scientist working on democracy, governance, and social cohesion."
  navbar:
    right:
      - text: CV
        href: cv.qmd
      - text: Publications
        href: publications.qmd
      - text: Pictures
        href: pictures.qmd

format:
  html:
    theme:
      light: [cosmo, styles.scss]
    toc: false
    page-layout: full
    include-in-header:
      text: '<meta name="google-site-verification" content="d9QWnWDzLtX7ZNqzBEEGg6mCYW7MQCTSgyORNH1W5ec" />'
    smooth-scroll: true
    link-external-newwindow: true
